---

- include: packages.yml
- include: networking.yml
- include: iptables.yml
- include: libvirt.yml
- include: lvm.yml
- include: virtual-machines.yml

- name: install reset workshop script from template
  template:
    src: "usr/local/bin/stx-reset-workshop"
    dest: "/usr/local/bin/stx-reset-workshop"
    mode: "0755"
  tags:
    - reset_script

- name: tool dir exist
  file:
    path: /home/student/tools/
    state: directory
    user: student
    mode: '0755'

- name: download stx-openstack charts
  get_url:
    url: "{{ item }}"
    dest: "/home/student/tools/{{ item | basename }}"
    mode: 0755
  with_items:
    - "{{ stx_openstack_charts_url }}"
    - "{{ unlock_script_url }}"
    - "{{ cirros_image_url }}"

- name: "judge localhost.yml is exits"
  stat: 
    path: /home/student/tools/localhost.yml
  register: config_file

- block:
  - name: create files from template
    template:
      src: "{{item}}"
      dest: "/home/student/tools/{{item}}"
      mode: 0755
    with_items:
      - "localhost.yml"
      - "admin-login.yaml"
      - "dashboard-values.yaml"
      - "openstack_rc"
      - "setup-openstack.sh"
  when: not config_file.stat.exists or registry == "local"