---

- include: packages.yml
- include: networking.yml
- include: iptables.yml
- include: libvirt.yml
- include: lvm.yml
- include: virtual-machines.yml

- name: install reset workshop script from template
  template:
    src: "usr/local/bin/stx-reset-workshop"
    dest: "/usr/local/bin/stx-reset-workshop"
    mode: "0755"
  tags:
    - reset_script


- name: download stx-openstack charts
  get_url:
    url: "{{ stx_openstack_charts_url }}"
    dest: "/home/student/{{ stx_openstack_charts_name }}"
    mode: 0755

- name: create localhost.yml from template
  template:
    src: "localhost.yml"
    dest: "/home/student/localhost.yml"
    mode: 0755

- name: download unlock host script
  get_url:
    url: "{{ unlock_script_url }}"
    dest: "/home/student/{{ unlock_script_url | basename}}"
    mode: 0755