---
local_registry: localhost:5000
gcr_registry: gcr.azk8s.cn/
k8s_registry: gcr.azk8s.cn/google-containers/

images:
  starlingx:
    names:
    - starlingx/stx-placement
    - starlingx/stx-nova
    - starlingx/stx-neutron
    - starlingx/stx-keystone
    - starlingx/stx-horizon
    - starlingx/stx-heat
    - starlingx/stx-gnocchi
    - starlingx/stx-glance
    - starlingx/stx-cinder
    - starlingx/stx-ceilometer
    - starlingx/stx-barbican
    - starlingx/stx-panko
    - starlingx/stx-ironic
    - starlingx/stx-aodh
    - starlingx/stx-keystone-api-proxy
    - starlingx/stx-nova-api-proxy
    - starlingx/stx-libvirt
    - starlingx/stx-ovs
    - starlingx/k8s-cni-sriov
    - starlingx/stx-mariadb
    - starlingx/k8s-plugins-sriov-network-device
    tags:
    - master-centos-stable-latest
    - rc-2.0-centos-stable-latest
  docker:
  - rabbitmq:3.7-management
  - kolla/ubuntu-source-nova-novncproxy:ocata
  - rabbitmq:3.7.13-management
  - rabbitmq:3.7.13
  - nfvpe/multus:v3.2
  - xrally/xrally-openstack:1.3.0
  - openstackhelm/mariadb:10.2.18
  - openstackhelm/neutron:ocata
  - port/ceph-config-helper:v1.10.3
  - osixia/keepalived:1.4.5
  - mariadb:10.2.13
  - memcached:1.5.5
  - prom/memcached-exporter:v0.4.1
  - openstackhelm/ceph-daemon:latest
  - docker:17.07.0
  - kbudde/rabbitmq-exporter:v0.21.0
  - nginx:1.13.3
  - prom/mysqld-exporter:v0.10.0
  quay:
  - quay.io/airshipit/armada:dd2e56c473549fd16f94212b553ed58c48d1f51b-ubuntu_bionic
  - quay.io/airshipit/armada:8a1638098f88d92bf799ef4934abe569789b885e-ubuntu_bionic
  - quay.io/calico/node:v3.6.2
  - quay.io/calico/cni:v3.6.2
  - quay.io/calico/kube-controllers:v3.6.2
  - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
  - quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11
  - quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
  k8s:
  - k8s.gcr.io/kube-proxy:v1.13.5
  - k8s.gcr.io/kube-controller-manager:v1.13.5
  - k8s.gcr.io/kube-apiserver:v1.13.5
  - k8s.gcr.io/kube-scheduler:v1.13.5
  - k8s.gcr.io/coredns:1.2.6
  - k8s.gcr.io/pause:3.1
  - k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
  - k8s.gcr.io/kube-apiserver:v1.16.0
  - k8s.gcr.io/kube-controller-manager:v1.16.0
  - k8s.gcr.io/kube-proxy:v1.16.0
  - k8s.gcr.io/kube-scheduler:v1.16.0
  - k8s.gcr.io/coredns:1.6.2
  gcr:
  - gcr.io/kubernetes-helm/tiller:v2.13.1
  - gcr.io/google_containers/defaultbackend:1.0
