---
- name: registry dir exist
  file:
    path: /var/lib/registry
    state: directory
    mode: '0755'

- name: run docker registry
  become: yes
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
    - "5000:5000"
    volumes:
    - "/var/lib/registry:/var/lib/registry"
